import type { BriefingView, WorkItem } from './work-api.js';
export const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const sectionNames={attention:'Needs your attention',updates:'Topic updates',waiting:'Waiting on others',upcoming:'Today and next'};
const stamp=(value:string)=>new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
export function briefingNavigation(data:BriefingView|undefined,selected:string,selectedDate=''){
    return `<header class="work-list-header"><span class="work-eyebrow">Executive assistant</span><h2>Your morning briefing</h2><p>The developments and decisions that need you.</p></header><div class="work-rows"><button class="work-row active" data-work="brief-home"><i class="ti ti-news" aria-hidden="true"></i><strong>Morning edition</strong></button>${Object.entries(sectionNames).map(([id,name])=>`<button class="work-row" data-work="brief-section" data-value="${id}"><i class="ti ti-${id==='attention'?'flag':id==='updates'?'message-circle':id==='waiting'?'clock':'calendar'}" aria-hidden="true"></i><strong>${name}</strong></button>`).join('')}<button class="work-row" data-work="brief-section" data-value="since"><i class="ti ti-refresh" aria-hidden="true"></i><strong>Since your briefing</strong></button><div class="briefing-editions"><label>Previous editions<select class="form-select form-select-sm" data-work-select="edition" aria-label="Briefing edition"><option value="">Latest edition</option>${(data?.editions??[]).map(e=>`<option value="${e.id}" ${selected===e.id?'selected':''}>${escape(e.date)}${e.revision>1?` · revision ${e.revision}`:''}</option>`).join('')}</select></label><label>Browse by date<input type="date" class="form-control form-control-sm" data-work-select="edition-date" aria-label="Briefing date" value="${escape(selectedDate)}"></label></div></div>`;
}
export function briefingArticle(data:BriefingView|undefined){
    if(!data)return '<div class="work-welcome"><h2>Opening your briefing…</h2></div>';
    const edition=data.edition;
    if(!edition&&data.requestedDate)return `<div class="work-welcome"><h2>No saved edition for ${escape(data.requestedDate)}</h2><p>Choose another date or the latest edition.</p></div>`;
    if(!edition)return `<div class="work-welcome"><i class="ti ti-news" aria-hidden="true"></i><h2>Your first morning edition</h2><p>${data.coverage.pending?'Your mail is being reviewed. The first edition will use reviewed work and show its coverage.':'Prepare a briefing from the work reviewed so far.'}</p><button class="btn btn-primary" data-work="prepare" ${data.status.running?'disabled':''}>${data.status.running?'Preparing…':'Prepare briefing'}</button></div>`;
    const lookup=new Map(edition.items.map(i=>[i.id,i]));
    const entry=(item:WorkItem,text:string)=>`<button class="briefing-entry" data-work="select" data-id="${item.id}"><span><small>${escape(item.topic)}${item.certainty==='suggested'?' · Suggested':''}</small><strong>${escape(item.title)}</strong><span>${escape(text)}</span></span><i class="ti ti-chevron-right" aria-hidden="true"></i></button>`;
    return `<article class="briefing-paper" aria-label="Daily email briefing"><header class="briefing-masthead"><span class="work-eyebrow">Dispatch · morning edition</span><h1>${new Date(`${edition.date}T12:00:00`).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</h1><p>Prepared ${escape(stamp(edition.preparedAt))}${edition.revision>1?` · Revision ${edition.revision}`:''}</p><p class="briefing-coverage">${edition.coverage.reviewed} reviewed conversations and imports · Indexed mail since ${escape(new Date(edition.coverage.from).toLocaleDateString())}${!edition.coverage.complete?' · Partial review':''}${edition.selection&&edition.selection.total>edition.selection.included?' · '+edition.selection.included+' of '+edition.selection.total+' work records considered':''}</p>${edition.coverage.ingestionAt?`<p class="briefing-coverage">Source changes checked ${escape(stamp(edition.coverage.ingestionAt))}${edition.coverage.mailState!=='ready'?' · Mail synchronization is '+escape(edition.coverage.mailState):''}</p>`:''}<button class="btn btn-sm btn-ghost-secondary briefing-revise" data-work="prepare" ${data.status.running?'disabled':''}><i class="ti ti-refresh" aria-hidden="true"></i>${data.status.running?'Preparing…':'Create revised edition'}</button></header>
    <section class="briefing-lead"><h2>At a glance</h2>${edition.content.lead.length?edition.content.lead.map(l=>`<p>${escape(l.text)}</p><div class="briefing-citations">${l.itemIds.map(id=>`<button class="work-link" data-work="select" data-id="${id}">${escape(lookup.get(id)?.topic??'Source')}</button>`).join(' · ')}</div>`).join(''):edition.items.length?'<p>Read the developments and attention items below.</p>':'<p>No attention items were found in the sources reviewed for this edition.</p>'}</section>
    ${Object.entries(sectionNames).map(([id,name])=>{const entries=edition.content.entries.filter(e=>e.section===id);return `<section class="briefing-section" id="brief-${id}"><h2>${name}</h2>${entries.length?entries.map(e=>entry(lookup.get(e.itemId)!,e.text)).join(''):'<p class="briefing-muted">No items in this edition.</p>'}</section>`;}).join('')}
    <section class="briefing-section" id="brief-since"><h2>Since your briefing</h2><p class="briefing-muted">The morning edition stays saved. Later changes appear here.</p>${data.since.length?data.since.map(i=>entry(i,i.status==='done'?'Completed since this edition.':i.summary)).join(''):'<p class="briefing-muted">No new reviewed developments since this edition.</p>'}</section></article>`;
}
